services:
  daily_output:
    image: ghcr.io/szanzibar/daily-output:latest
    ports:
      - '${PORT:-4000}:4000'
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
